#!/usr/bin/env bash
set -eua

ptmp=$PWD/ptmp; rm -rf $ptmp; mkdir $ptmp

EXPNAM=$1 CDATE=$2 COMROT=${3:-${COMROT:-$ptmp/$USER}} ARCDIR=${4:-${ARCDIR:-$COMROT/archive}} TMPDIR=${5:-${TMPDIR:-$ptmp/$USER/f2o/tmpdir}}

FITDIR=$(cd $FITDIR; pwd); fitdir=$FITDIR/batrun

COMDAY=${COMDAY:-$COMROT}

set +x
echo -------------------------------------------------------------------------------------------------------------------
echo Starting the runfits for:
echo -------------------------------------------------------------------------------------------------------------------
echo "EXPNAM    " $EXPNAM       # argument 1 - experiment name    - required  
echo "CDATE     " $CDATE        # argument 2 - date of validation - required
echo "COMROT    " $COMROT       # argument 3 - COMROT directory   - optional - defaults to $ptmp/$USER  
echo "ARCDIR    " $ARCDIR       # argument 4 - ARCDIR directory   - optional - defaults to $COMROT/archive
echo "TMPDIR    " $TMPDIR       # argument 5 - TMPDIR directory   - optional - defaults to /ptmp/$USER/tmpdir
echo "COMDAY    " $COMDAY       # inheirited - dayfile directory  - optional - defaults to $COMROT     
echo "FITDIR    " $FITDIR       # inheirited - Fit2obs batrun dir - optional - defaults to $(dirname $0)
echo "ACCOUNT   " $ACCOUNT      # inheirited - project code       - required - defaults to nothing
echo "COM_INA   " $COM_INA      # inheirited - project code       - required - defaults to nothing
echo "COM_INF   " $COM_INF      # inheirited - project code       - required - defaults to nothing
echo "OUTPUT_FILETYPE " $OUTPUT_FILETYPE    # inheirited - project code       - required - either nemsio or netcdf defaults to sigio
echo -------------------------------------------------------------------------------------------------------------------
set -x

mkdir -p $COMROT $COMDAY
ACCOUNT=da-cpu

#BSUB -o $COMDAY/FITS.$EXPNAM.$CDATE.$$
#BSUB -J FITS.$EXPNAM.$CDATE
#BSUB -P $ACCOUNT
#BSUB -n 4
#BSUB -R span[ptile=1]
#BSUB -R affinity[core(1):distribute=balance]
#BSUB -W ${TIMELIM:-02:00}
#BSUB -q ${CUE2RUN:-dev}

cat<<eof | sbatch
#!/bin/bash --login
#SBATCH --job-name=FITS.$EXPNAM.$CDATE --time=20:00
#SBATCH --nodes=1 --ntasks=4
#SBATCH --output=$COMDAY/FITS.$EXPNAM.$CDATE.$$
#SBATCH --account=$ACCOUNT
#SBATCH --partition=debug  
#SBATCH -q debug 


#!/usr/bin/env bash
set -euax

set +x
 module purge
 module load intel/2020.2
 module load impi/2020.2
 module load netcdf/4.7.4
 module list
set -x

export OMP_NUM_THREADS=${FITOMP:-1}
export KMP_AFFINITY=disabled
export MPIRUN="srun -n 4 --exclusive"
export ONERUN="srun -n 1 --exclusive"

export ARCDIR=$ARCDIR
export TMPDIR=$TMPDIR
export fitdir=$fitdir

export CHGRP_RSTPROD=NO     

time $fitdir/runfits $EXPNAM $CDATE $COMROT

chmod -R 700 $ptmp

eof

