#!/bin/bash
set -euax

EXPNAM=$1 CDATE=$2 COMROT=${3:-$STMP/$USER} ARCDIR=${4:-$COMROT/archive} TMPDIR=${5:-$STMP/$USER/tmpdir}

ACCOUNT=${ACCOUNT:-CFS-T2O}
CUE2RUN=${CUE2RUN:-dev}

echo -------------------------------------------------------------------------------------------------------------------
echo Starting the runfits for:
echo -------------------------------------------------------------------------------------------------------------------
echo "EXPNAM    " $EXPNAM       # argument 1 - experiment name    - required  (can be prod in which case COMROT is moot)
echo "CDATE     " $CDATE        # argument 2 - date of validation - required 
echo "COMROT    " $COMROT       # argument 3 - COMROT directory   - optional - defaults to /stmp/$USER
echo "ARCDIR    " $ARCDIR       # argument 4 - ARCDIR directory   - optional - defaults to $COMROT/archive 
echo "TMPDIR    " $TMPDIR       # argument 5 - TMPDIR directory   - optional - defaults to /stmp/$USER/tmpdir
echo "ACCOUNT   " $ACCOUNT      # inheirited - project code       - required - defaults to nothing  
echo -------------------------------------------------------------------------------------------------------------------

fitdir=$(dirname $0); fitdir=$(cd $fitdir; pwd)
COMDAY=${COMDAY:-$COMROT/logs/$CDATE}

set -euax          

cat<<EOF | qsub
#PBS -S /bin/ksh
#PBS -A $ACCOUNT
#PBS -N FITS.$EXPNAM.$CDATE
#PBS -o $COMDAY/fit2obs.log
#PBS -q ${FITCUE:-batch}
#PBS -l ${FITPPN:-"nodes=3:ppn=1"}
#PBS -l walltime=${FITTIM:-"01:00:00"}
#PBS -d `pwd`
#PBS -j oe
#PBS -V

set -euax

export OMP_NUM_THREADS=${FITOMP:-1}
export MPIRUN='mpirun'
export KMP_STACKSIZE=100M
export MPI_BUFS_PER_PROC=256
export MPI_BUFS_PER_HOST=256
export MPI_GROUP_MAX=256
ulimit -s 20000000; ulimit -a

export CDATE=$CDATE
export EXP=$EXPNAM
export COM_IN=$ROTDIR
export COM_INA=$ROTDIR
export COM_INF=$ROTDIR/vrfyarch

export fitdir=$fitdir
export ARCDIR=$ARCDIR
export TMPDIR=$TMPDIR
export ACPROFit=${ACPROFit:-YES}
export NEMS=${NEMS:-YES}   
export PRVT=${PRVT:-$HOMEgfs/fix/fix_gsi/prepobs_errtable.global}
export HYBLEVS=${HYBLEVS:-$HOMEgfs/fix/fix_am/global_hyblev.l65.txt}

time $fitdir/runfits $EXPNAM $CDATE $COMROT

EOF
