#!/bin/sh
set -aeu

[ $# -ge 1 ] && plat=$1 || plat=none ; mkdir -p ../../exec

if [ $plat = jibb ]; then
 export LIBD=/home/jwoollen/lib
 export LIBS="-L$LIB4 -lw3_4 -lbufr_4_64"
 export FLAGS="-O3 -g -traceback"
 export FCMP="ifort"
elif [ $plat = wcoss ]; then
 export LIBD=/nwprod/lib
 export LIBS="$BUFR_LIBd -L$LIBD -lw3nco_d"
 export LIBS="$BUFR_LIB4 $W3NCO_LIB4      "
 export FLAGS="-O3 -g -traceback -r8 -i4"
 export FCMP="ifort"
elif [ $plat = gaea ]; then
 export LIBD=/lustre/f1/dev/ncep/Jack.Woollen/nwprod/lib
 export LIBS="-L$LIBD -lw3nco_4 -lbufr_4_64"
 export FLAGS="-O3 -g -traceback"
 export FCMP="ftn"
elif [ $plat = zeus ]; then
 export LIBD=/contrib/nceplibs/nwprod/lib            
 export LIBS="-L$LIBD -lw3nco_4 -lbufr_4_64"
 export FLAGS="-O3 -g -traceback"
 export FCMP="ifort"
elif [ $plat = theia ]; then
 export LIBD=/scratch3/NCEPDEV/nwprod/lib         
 export LIBS="-L$LIBD -lw3nco_4 -lbufr_4_64"
 export FLAGS="-O3 -g -traceback"
 export FCMP="mpiifort"
elif [ $plat = cray  ]; then
 export LIBS="$W3NCO_LIB4 $BUFR_LIB4"
 export FLAGS="-O3 -g -traceback"
 export FCMP="ftn"
elif [ $plat = dell  ]; then
 export LIBS="$W3NCO_LIB4 $BUFR_LIB4"
 export FLAGS="-O3 -g -traceback"
 export FCMP="mpiifort"
else
 echo "no recognized platform specified ($plat)"
 exit 99
fi

for NAME in cfs_bufrslupao cfs_bufrslslev cfs_bufrslsfc cfs_sfc cfs_raob cfs_acft cfs_acar cfs_surf; do
 export NAME; echo $NAME
 make -f Makefile clean
 make -f Makefile
 make -f Makefile clean
 mv $NAME ../../exec 
done
